Feature/#9 text style
Nexters/JYP_Android pull request #15
Opened 2022-08-04 16:21 UTC by yxnsx

2022-08-06 15:45 UTC, sodp5 requested changes

2022-08-06 15:45 UTC, sodp5 commented on core_ui/src/main/java/com/jyp/jyp_design/ui/text/BodyText.kt
> +}
전체적으로 모든 TextView에 Modifier를 넣어줘야 할것 같아!

```
@Composable
fun SomeText(
    modifier: Modifier = Modifier,
) {
    Text(
        modifier = modifier,
        // attributes
    )
}
```

2022-08-06 15:45 UTC, sodp5 commented on core_ui/src/main/java/com/jyp/jyp_design/ui/typography/style/BodyTextStyle.kt
> +) = when (type) {
여기는 Composable 어노테이션을 제거하면 좋을것 같아
Composable함수는 Unit을 반환하는 룰이 있어!

2022-08-06 15:45 UTC, sodp5 commented on core_ui/src/main/java/com/jyp/jyp_design/ui/typography/style/BodyTextStyle.kt
> +) = when (type) {
여기서는 TextStyle을 반환한다는것이 명확해보이기는 하지만,
라인이 길 때는 return type을 명시하는게 좋다고 생각해!
취향의 차이라고도 생각해서 꼭 고칠 필요는 없을것 같아

2022-08-07 09:35 UTC, yxnsx commented on core_ui/src/main/java/com/jyp/jyp_design/ui/text/BodyText.kt
> +}
수정했습니다 ~~!

2022-08-07 09:36 UTC, yxnsx commented on core_ui/src/main/java/com/jyp/jyp_design/ui/typography/style/BodyTextStyle.kt
> +) = when (type) {
이 부분도 수정했습니다 ~!

2022-08-07 10:15 UTC, sodp5 approved these changes

2022-08-07 10:15 UTC, merged