Feature/#31 search place - 카카오 로컬 api 및 카카오맵 적용
Nexters/JYP_Android pull request #59
Opened 2022-09-27 07:18 UTC by yxnsx

local.properties 파일에 kakao_native_app_key 값 넣고 빌드해주십셔
카카오맵 안뜨는건 버그로 따로 빼서 수정하겠습니다,,

2022-10-04 16:18 UTC, sodp5 requested changes
고생했습니당~~

2022-10-04 16:18 UTC, sodp5 commented on feature_add_place/build.gradle
> +        minSdk 21
이거 23으로 수정해줘!

2022-10-04 16:18 UTC, sodp5 commented on feature_add_place/src/main/AndroidManifest.xml
> +        tools:targetApi="n">
이거 타겟 n으로 설정한 이유가 있을까??
앱모듈은 기본을 23 (m) 으로 사용중이라서!

2022-10-04 16:18 UTC, sodp5 commented on feature_add_place/src/main/java/com/jyp/feature_add_place/data/mapper/SearchPlaceResponseModelMapper.kt
> +fun KakaoLocalResponseModel.Place.toSearchPlaceResultModelList() = SearchPlaceResultModel(
List를 반환하지 않는데 List라는 네이밍이 혼동을 줄 수 있을것 같아!

2022-10-04 16:18 UTC, sodp5 commented on feature_add_place/src/main/java/com/jyp/feature_add_place/di/SearchPlaceModule.kt
> +    }
GetSearchPlaceUseCase.kt 에 Inject가 이미 있어서 이건 제거해도 정상 동작할거야

2022-10-04 16:18 UTC, sodp5 commented on feature_add_place/src/main/java/com/jyp/feature_add_place/domain/SearchPlaceUseCase.kt
> +    }
operator fun invoke() 로 작성할 수 있을까?
UseCase는 어차피 하나의 기능만 갖기 때문에 클래스명이 이미 무슨 기능을 할 지 잘 나타낸다고 생각해서!

2022-10-04 16:18 UTC, sodp5 commented on feature_add_place/src/main/java/com/jyp/feature_add_place/presentation/PlaceInfoActivity.kt
> +    }
논리상으로 장소가 없으면 안되는 케이스가 없지 않아?
개발자의 실수로 인한 오류랑 API 오류랑 헷갈릴것 같아서
차라리 extra가 없으면 exception을 던지거나 finish를 해주면 어떨까?

2022-10-04 16:18 UTC, sodp5 commented on feature_add_place/src/main/java/com/jyp/feature_add_place/presentation/PlaceMapActivity.kt
> +    }
여기도 마찬가지로 없어야하는 케이스가 없을것 같아!

2022-10-04 16:18 UTC, sodp5 commented on feature_add_place/src/main/java/com/jyp/feature_add_place/presentation/PlaceMapActivity.kt
> +    private val viewBinding get() = _viewBinding!!
```suggestion
    private val viewBinding: ActivityPlaceMapBinding by lazy {
        ActivityPlaceMapBinding.inflate(layoutInflater)
    }
```
backing property 대신 이렇게 하면 더 간단해보일것 같아

2022-10-04 16:18 UTC, sodp5 commented on feature_add_place/src/main/java/com/jyp/feature_add_place/presentation/PlaceMapActivity.kt
> +private fun ComposablePlaceInfoBottomSheet(
화면을 보여주는 용도로 들어가있는걸까??
자세히는 못봐서 어떤역할을 하고있는진 잘 모르겠어 ㅠㅠ
나중에 Activity 로직 파악할 때 같이 봐야하는 부분인지 체크하게 될것같아서
꼭 여기 있어야 하는게 아니라면 파일 분리해두면 좋을것 같아!

2022-10-04 16:18 UTC, sodp5 commented on feature_add_place/src/main/java/com/jyp/feature_add_place/presentation/SearchPlaceActivity.kt
> +    @RequiresApi(Build.VERSION_CODES.M)
build.gradle에서 minsdk 버전 변경하고 지우면 될것같아

2022-10-04 16:18 UTC, sodp5 commented on feature_add_place/src/main/java/com/jyp/feature_add_place/presentation/SearchPlaceActivity.kt
> +@RequiresApi(Build.VERSION_CODES.M)
여기도 제거

2022-10-05 16:51 UTC, yxnsx commented on feature_add_place/src/main/AndroidManifest.xml
> +        tools:targetApi="n">
`android:networkSecurityConfig` 속성이 api 24 이상부터 설정 가능해서.. !
카카오 지도 api가 http 기반이라 network_security_config 파일로 도메인 설정이 필요합니다 ..

2022-10-16 09:55 UTC, sodp5 commented on feature_add_place/src/main/AndroidManifest.xml
> +        tools:targetApi="n">
android:usesCleartextTraffic 이거만 있어도 됐던거 같은데
android:networkSecurityConfig 이거 없어도 되지 않아??

우리 min을 23으로 두고 작업하고 있었어서 24부터만 되는 api는 사용하면 안될것 같아ㅠ
android:networkSecurityConfig 이게 꼭 필요한거면 아예 min 자체를 24로 바꿔야 할것같아

2022-10-16 09:55 UTC, sodp5 commented on feature_add_place/src/main/java/com/jyp/feature_add_place/presentation/PlaceMapActivity.kt
> +private fun ComposablePlaceInfoBottomSheet(
이거 bottom sheet는 파일 분리해줘!!

2022-10-16 10:03 UTC, yxnsx commented on feature_add_place/src/main/AndroidManifest.xml
> +        tools:targetApi="n">
오키오키 !! 
근데 생각해보니 영모가 우리 카카오맵이 아니라 구글맵 사용하기로 했었다고 해서
구글맵으로 다시 작업해야 하네요,, 일단 싹 날리겠슴다 ,,

2022-10-16 10:09 UTC, yxnsx commented on feature_add_place/src/main/java/com/jyp/feature_add_place/presentation/PlaceMapActivity.kt
> +private fun ComposablePlaceInfoBottomSheet(
<img width="447" alt="스크린샷 2022-10-16 오후 7 05 28" src="https://user-images.githubusercontent.com/47806943/196029617-f98002a6-3646-467c-aee0-1dcc138e450b.png">

이거 장소 검색 결과 맵뷰 화면 하단에 뜨는 바텀시트를 단순 UI로만 구현해둔건데도 빼야할까? 
왜 빼야 하는건지를 잘 모르겠네ㅠ..

2022-10-23 08:18 UTC, sodp5 requested changes

2022-10-23 08:18 UTC, sodp5 commented on feature_add_place/src/main/java/com/jyp/feature_add_place/di/SearchPlaceModule.kt
> +}
여기 interface나 abstract class 하나만 두는게 더 간단해 보일것 같아!@Module
```
@InstallIn(SingletonComponent::class)
    interface BindsModule {
        @Binds
        @Singleton
        fun bindSearchPlaceRepositoryInterface(
            searchPlaceRepositoryImpl: SearchPlaceRepositoryImpl
        ): SearchPlaceRepositoryInterface
    }
```
이렇게만??
그리구 이런 API는 ViewModel에서 호출하게 되니까 ViewModelComponent로 해줘!

2022-10-23 08:18 UTC, sodp5 commented on feature_add_place/src/main/java/com/jyp/feature_add_place/presentation/PlaceMapScreen.kt
> +                painter = painterResource(com.jyp.jyp_design.R.drawable.icon_left_arrow),
이런것들 앞에 패키지명 숨겨주기 위해서 JypPainter 에 넣어두고 쓰는것 어때??
난 일단 몇 개 그렇게 해뒀어

2022-10-23 08:18 UTC, sodp5 commented on feature_add_place/src/main/java/com/jyp/feature_add_place/presentation/UiState.kt
> +sealed class UiState {
떠오르는건 없는데, 여기 조금 더 구체적인 네이밍 없을까??
네트워크와 관련된건지 아니면 앱의 자체적인 로딩 등을 처리하는건지 불명확 한거같아

2022-10-23 08:18 UTC, sodp5 commented on feature_add_place/src/main/java/com/jyp/feature_add_place/presentation/UiState.kt
> +sealed class UiState {
UiState 라는 클래스는 UI에 관련된 정보들을 갖고있을것 같다고 생각하고 읽었는데 (장소명 같은)
로딩이나 성공여부를 갖고 있길래!

2022-10-23 08:18 UTC, sodp5 commented on feature_add_place/src/main/java/com/jyp/feature_add_place/util/Extensions.kt
> +@RequiresApi(Build.VERSION_CODES.M)
이거 없어도 될것같아

2022-10-23 08:18 UTC, sodp5 commented on feature_add_place/src/main/java/com/jyp/feature_add_place/util/Extensions.kt
> +@RequiresApi(Build.VERSION_CODES.M)
이것도 없어도 될것같아

2022-10-23 08:18 UTC, sodp5 commented on feature_add_place/src/main/java/com/jyp/feature_add_place/util/Extensions.kt
> +fun isNetworkActivated(context: Context): Boolean {
여기도 확장함수로 만들면 어때?
38번 라인도 this 없앨 수 있을것 같아

2022-10-23 08:18 UTC, sodp5 commented on feature_add_place/src/main/java/com/jyp/feature_add_place/util/Extensions.kt
> +    return when (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
우리 min 버전이 23이라서 없어도 될것같아!

2022-10-23 09:17 UTC, sodp5 approved these changes
고생했어!!!

2022-10-23 09:18 UTC, merged