Feature/#63 questions
Nexters/JYP_Android pull request #69
Opened 2022-12-11 04:57 UTC by yxnsx

2022-12-18 12:23 UTC, sodp5 requested changes
여행 질문 타이틀 색상 80이 아닌 90으로 수정해줘!

피그마 상으로 봤을 때 여행 카드의 초기 상태가 반투명이 아니라,
선택한 카드가 있을 때 다른 카드가 반 투명 해지는것 같아!

R.drawable.icon_check 대신에
JypPainter.check 이걸로 대체해줘
그림자 있는 리소스는 png파일로 해야 제대로 나오더라구!

체크 아이콘 사이즈가 피그마 상으로 하늘색 영역만 24로 되어있어서
우리가 가지고 있는 이미지로 24 사이즈를 주면 안될것 같아
적당히 30정도로 늘리거나
디자이너한테 물어봐서 흰 배경과 그림자를 포함한 사이즈로 수정하면 좋을것 같아

2022-12-18 12:26 UTC, sodp5 requested changes

2022-12-18 12:26 UTC, sodp5 commented on feature_question/src/main/java/com/jyp/feature_question/presentation/QuestionScreen.kt
> +                    onClick = { onClickQuestionOption(question.index, index) }
여기 리플효과 없애주면 좋을것 같아!
```
.clickable(
                interactionSource = remember { MutableInteractionSource() },
                indication = null
            ) {
```

2022-12-25 06:13 UTC, yxnsx commented on feature_question/src/main/java/com/jyp/feature_question/presentation/QuestionScreen.kt
> +                    onClick = { onClickQuestionOption(question.index, index) }
수정 완..!!!

2022-12-30 05:15 UTC, sodp5 approved these changes

2022-12-30 05:15 UTC, merged