Feature/#75 api join invitation
Nexters/JYP_Android pull request #93
Opened 2023-02-19 05:59 UTC by yxnsx

2023-03-05 15:34 UTC, sodp5 requested changes

2023-03-05 15:34 UTC, sodp5 commented on core_network/src/main/java/com/jyp/core_network/jyp/ApiResult.kt
> +fun<Nothing> ApiResult<Nothing>.onFailure(action: (JypFailureResponse) -> Unit): ApiResult<Nothing> {
여기는 이렇게 하면 기존이랑 동일해서 그냥 T로 돌려두는게 좋을것 같아

만약 Generic을 Nothing으로 하려는 의도였다면 onFailure와 onSuccess간에 순서가 생기게 되서
좋지 않은것 같아

예를 들면 Nothing인 경우 아래처럼 쓰고싶어도 쓸 수 없게 돼!
```
apiResult
    .onFailure { }
    .onSuccess { }
```

2023-03-05 15:34 UTC, sodp5 commented on core_network/src/main/java/com/jyp/core_network/jyp/ApiResult.kt
> +    }
onFailure 내부에서 분기태우는거보다 onJypApiException 과 같은 함수를 추가로 만들어줄 수 있을까??

에러 처리를 두 개 분리해서 하는게 귀찮을 순 있는데 단순 에러처리를 할 수 없게 돼서..ㅠ

그러면 apiResult 함수에서 jypApi 에러인지 확인하는 로직이 들어가게 될 것 같아
onFailure와 같은 함수는 builder 패턴과 비슷한 형태로 사용하고 있었어서 로직이 이 함수에 있는게 더 자연스러운것 같기도 하고!
```
inline fun <T : Any> apiResult(call: () -> JypBaseResponse<T>): ApiResult<T> {
    return runCatching {
        ApiResult.Success(call.invoke().data)
    }.getOrElse {
        if (it is HttpException) {
            val response = it.response()?.errorBody()?.charStream()
            val error = Gson().fromJson(response, JypFailureResponse::class.java)
            ApiResult.JypApiException(error)
        } else {
            ApiResult.Failure(it)
        }
    } as ApiResult<T>
}
```

2023-03-11 10:25 UTC, yxnsx commented on core_network/src/main/java/com/jyp/core_network/jyp/ApiResult.kt
> +    }
이 부분 JypApiException이 필요한 경우 throwable에 적용해서 사용할 수 있는 확장함수 만들어서 처리하는거로 수정했어!

내가 기존에 작성했던 코드랑 마찬가지로 위에 작성해준 코드도 발생한 exception이 http exception인 경우에는 JypApiException로 처리될 수 밖에 없을 것 같아서..!

뷰에서 uiState 받아서 
``` kotlin
is UiState.Failure -> {
    uiState.throwable.printStackTrace()
    uiState.throwable.toJypApiFailure()?.let {
        showToast(it.message)
    }
}
```
이런 식으로 처리할 수 있게 해봤는데 괜찮으신가엽..?

2023-03-16 02:20 UTC, sodp5 commented on core_network/src/main/java/com/jyp/core_network/jyp/ApiResult.kt
> +    }
JypApi 를 호출해서 나오는 HTTP Exception은 모두 JypApiException인게 자연스러울것 같은데 어떻게 생각해??
우리가 정의하지 않은 에러도 있을 수 있겠지만 그런 케이스는 서버에 정의를 해달라고 요청하는게 서버쪽 구현 방향에도 맞을것 같아서!

2023-03-16 11:21 UTC, sodp5 approved these changes

2023-03-16 11:21 UTC, merged